### ISSUE TITLE
Derive for generic Argument Structs

### ISSUE THREAD

**Issue by ysndr** [pacak/bpaf#147]
Currently generic structs cannot derive Bpaf

```rust
#[derive(Bpaf, Clone, Debug)]
pub struct Args<T: FromStr> {
   something: T
}
```

results in 

```
error: Expected named or unnamed struct
  --> crates/prog/src/commands/package.rs:25:16
   |
25 | pub struct Args<T: FromStr> {
   |                ^
```

it would be nice to have derives for those as otherwise i have to extract the generic parts and parse them separately with manual parser functions.
Not too big of a deal but it would surely be easier to just use with `#[bpaf(external(args::<MyType>)]`

**Comment by pacak** [comment]
For a simple structure that contains a single polymorphic struct derived code might look like this:

```rust
    #[derive(Debug, Clone, Eq, PartialEq)]
    struct Poly<T> {
        field: T,
    }

    fn poly<T>(name: &'static str) -> impl Parser<Poly<T>>
    where
        T: FromStr + 'static,
        <T as FromStr>::Err: std::fmt::Display,
    {
        let field = long(name).argument("ARG");
        construct!(Poly { field })
    }
```
Then you'll have to add extra constraints for any operation you add on top of parsing - `guard`, `parse`, etc. 

To use it with `external` `bpaf_derive` will have to replicate all the constraints from the external function - user will have to specify it since this info is not available at macro resolution level. 

While this is possible to add some syntax to let users pass all this info this makes it so user will have to write in a custom macro language without help from rust-fmt, rust-analyzer and the rest of the tools. I think at this point it's worth moving some of the logic from derive to combinatoric style.
