### ISSUE TITLE
Provide a counterpart to `.run()` usable for unit tests

### ISSUE THREAD

**Issue by Shnatsel** [pacak/bpaf#2]
It would be nice to be able to write unit tests for the argument parser - e.g. that certain combinations of arguments are accepted or rejected, that the custom code in `.map()` or `.parse()` is correct, or when reimplementing/mimicking an existing interface with bpaf and keeping the tests from the previous ones to avoid API breaks.

Right now parsing can only be performed with `.run()`, which gets the data from the command line, and prints to stdout. There doesn't seem to be a way to pass a hardcoded list of arguments or capture the output, which is necessary for unit tests.

This could be solved by providing a function that accepts `T: IntoIterator<OsStr>` and writes to an arbitrary `T: Write`, or at least non-generic version of that such as `&[OsStr]`, so that the parser could be unit-tested.

**Comment by pacak** [comment]
There's some private API to do exactly that, I just made it public: 3af6481e45dbf1e51738aaf42e975ff3bcd591cf. For now you can use git version, I'll make a release in a day or two once I figure out proper documentation for that.

You can find some examples here:

https://github.com/pacak/bpaf/blob/master/src/tests.rs

**Comment by pacak** [comment]
Pushed some more changes with documentation. Please let me know if it solves your problem. If it is - I'll publish it to crates.io.

**Comment by Shnatsel** [comment]
Thank you for such a quick implementation!

I have added unit testing to `cargo supply-chain` in https://github.com/rust-secure-code/cargo-supply-chain/commit/b05efdeeb00f32639a7bfc8c401754aade0b1600, and the API for that looks great to me!

The `.unwrap_stdout()` and `.unwrap_stderr()` however are a little confusing, especially following `.unwrap_err()`. Perhaps they would be more clear if named `.capture_stderr()` or some such?

I'm also not fond of panicking if nothing is printed, because it makes it difficult to verify that nothing is printed. Perhaps return an empty string if there is no output?

Both of the `capture_*` methods could use code examples as well. I think `--help` and passing an invalid flag would make good examples for stdout and stderr respectively.

Thanks again!

**Comment by Shnatsel** [comment]
Also, should the `unwrap_*` methods return `String` or `OsString`? I think testing handling of non-UTF-8 arguments could be valuable, and they would not be expressible in a `String`.

**Comment by pacak** [comment]
It is not really capturing anything. If parser detects --help or --version
it will always produce only something that can be consumed with
unwrap_stdout. Otherwise it will produce "stderr" generated either by the
parser if someone is missing or by user's guard or parse functions. API for
those is constructed to only produce a String. If you try to print
something inside map or parse - it will not be captured. Depending on a
test case you'll know what to use. Unwrap_stdout if you want to test
generated help or unwrap_stderr if you are testing parse/guard/ missing
parameters. Exact string reperentations are probably not stable between
versions.

In theory it should not be possible to print nothing at all - bpaf should
add at least a field name that failed to parse. Will check on that
tomorrow. I guess I'll add most of this email to docs as well.

**Comment by pacak** [comment]
Released 0.2.1
